import time
# time.sleep(2)
# print("\n\n\n\nIt's time to wake up Vinoth. The date is 14th October and the weather is 25 degree Celsius. A perfect time for jogging")
# time.sleep(2)
# print('wake me up after a few minutes i need a few more time to sleep')
# time.sleep(2)
# print("It's sunrise you have to wake up now")
# time.sleep(2)
# print("Tamil: dai eruma madu sikiram endri evlo neram thoonguva")
# time.sleep(2)
# print("i woke up")
# time.sleep(2)
# print("Tamil_trans: Iam still looking at you, you are still sleeping. Don't lie to me")
# time.sleep(2)
# print("do i have any meetings")
# time.sleep(2)
# print("Tamil_trans: You have no work. You are free the whole day. Wake up and run")
# time.sleep(2)
# print("its dark outside four clock no i need to sleep its midnight")
# time.sleep(2)
# print("I will forcefully wake you up if you don't wake up now the choice is yours")
# time.sleep(2)
# print("If the bike is on you have to be outside right?")
# time.sleep(2)
# print("you did not turn it on did you")
# time.sleep(2)
# print("The ignition is turned on")
print("\n\n\nIf you wear saree or churidar the chances will reduce sir\n\n\n")